### ISSUE TITLE
[Client-SDK]Block Diagram has Ubuntu OS v16.04 needs to be changed as Ubuntu OS v18.04

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#18]
Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/
Block Diagram 1 in Client SDK Overview Section, has Ubuntu OS v16.04 needs to be changed as Ununtu OS v18.04
<img width="475" alt="ModifyUbuntuVersion" src="https://user-images.githubusercontent.com/69335071/91719676-6090d800-ebb3-11ea-8553-902e12c01c62.png">

**Comment by nbmaiti** [comment]
- #39
