### ISSUE TITLE
[Client SDK]Remove Ubuntu 16.04 , Modify Openssl 1.1.1g and align bulletins properly

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#19]
Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/
In table of Prerequisites section , First row Ubuntu version 16.04 should be removed , modify openssl version to 1.1.1g and align bulletins properly.
<img width="517" alt="RemoveUbuntu" src="https://user-images.githubusercontent.com/69335071/91747239-75816180-ebdb-11ea-8549-8d6bc0ed77fd.png">

**Comment by nbmaiti** [comment]
#39
