### ISSUE TITLE
[Client SDK]Bulletin alignment needs correction, bulletin alignment in new line in Known issues and limitations

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#20]
Link: https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/
Within Known Issues and limitation section, bulletins were not alignes properly second bulletin should be in new line.
<img width="518" alt="BulletinAlignmentinnewline" src="https://user-images.githubusercontent.com/69335071/91747433-ce50fa00-ebdb-11ea-84dd-763c07533402.png">

**Comment by nbmaiti** [comment]
- #39

**Comment by nbmaiti** [comment]
- #39
