### ISSUE TITLE
[Client SDK]Ownership Proxy needs to be replaced with Ownership voucher

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#21]
Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/
Within Notes section of Device Initialization, Ownership proxy needs to be replaced with Ownership voucher 
<img width="556" alt="OwnershipProxyneedstobechangedtoOwnershipVoucher" src="https://user-images.githubusercontent.com/69335071/91799717-43a4e500-ec45-11ea-945d-a8736765f539.png">

**Comment by nbmaiti** [comment]
- #39
