### ISSUE TITLE
[Client SDK]In pre service info section,"touple" word is seen in document, whether its a typo for tuple.

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#23]
Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/
In SDO Module Flow, with Pre Service Info (PSI) Section , "touple" word is seen twice whether its a typo for tuple.
<img width="539" alt="toupletypo1" src="https://user-images.githubusercontent.com/69335071/91813504-6dafd480-ec50-11ea-8395-7d3d037a0a82.png">
<img width="525" alt="toupletypo2" src="https://user-images.githubusercontent.com/69335071/91813511-70122e80-ec50-11ea-8c04-04556ccc9d24.png">

**Comment by nbmaiti** [comment]
- #39
