### ISSUE TITLE
[Client SDK]Change DMS to SDO IOT Platform SDK

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#24]
Link : https://secure-device-onboard.github.io/docs/latest/reference/
In Terminology Section , in heading TO1 "DMS" is mentioned which should be changed as "SDO IOT Platform SDK"
In SDO Module Flow, with Pre Service Info (PSI) Section , "touple" word is seen twice whether its a typo for tuple.
<img width="524" alt="ChangeDMStoSDOIOTPlatformSDK" src="https://user-images.githubusercontent.com/69335071/91826941-db153280-ec5b-11ea-8d25-be96b204f290.png">

**Comment by nbmaiti** [comment]
- #39
