### ISSUE TITLE
[Client SDK]Punctuations needs to be corrected.

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#27]
Page Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/

Section Link: https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#device-initialization
In PunctuationsRequired Image : Replace "Running the device" with "Running the device,"[Within Notes]
<img width="533" alt="PunctuationsRequired" src="https://user-images.githubusercontent.com/69335071/91827926-1fed9900-ec5d-11ea-8605-1d8a184c3953.png">

Section Link: https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#owner-service-info-osi
In PunctuationsRequired2 Image : Replace "A module must expect to remain active unless it explicitly receives a deactivation message " with "A module must expect to remain active unless it explicitly receives a deactivation message,"[Within Owner Service Info(OSI) , third paragragh]
<img width="524" alt="PunctiationsRequired2" src="https://user-images.githubusercontent.com/69335071/91836169-09007400-ec68-11ea-92fc-06bd38fb30b5.png">

Section Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#device-service-info-dsi
In PunctuationsRequired3 Image : Replace "The module may choose to ignore the ‘index’ sent by the SDK but it is advisable for the module to return key-value data based on this index." with "The module may choose to ignore the ‘index’ sent by the SDK, but it is advisable for the module to return key-value data based on this index."[third paragragh]
<img width="527" alt="PunctuationsRequired3" src="https://user-images.githubusercontent.com/69335071/91836191-14539f80-ec68-11ea-8f7e-7297d5c60242.png">

Section Link: https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#device-service-info-dsi
In PunctuationsRequired4 Image : Replace "The very first key-value returned by a module (‘index’ zero) must be an activation value indicating whether the module is active or not. The key value must be “active” and the value must be “1” if the module is active or “0” if the module is not active. " with "The very first key-value returned by a module (‘index’ zero) must be an activation value indicating whether the module is active or not. The key value must be “active”, and the value must be “1” if the module is active or “0” if the module is not active. "[third paragraph]
<img width="530" alt="PunctuationsRequired4" src="https://user-images.githubusercontent.com/69335071/91836956-21bd5980-ec69-11ea-911a-57e9d5d295db.png">

**Comment by nbmaiti** [comment]
- #39
