### ISSUE TITLE
[IOT Platform SDK] Issues in introduction.md

### ISSUE THREAD

**Issue by himanshu7196** [secure-device-onboard/docs#30]
**Section: Introduction**

1.  In the first paragraph, it should be "..integration of an owner's IoT Platform..."

![image](https://user-images.githubusercontent.com/68280628/91840649-a65ea680-ec6e-11ea-8426-d950a1cbc9c1.png)

**Section: Components**

1.  Inconsistent indentation of different subsections. Bullets can be added to differentiate sections and subsections.

2.  In **_Components->TO0 scheduler:_**

The first line has Ownership Proxies instead of ownership voucher

![image](https://user-images.githubusercontent.com/68280628/91840976-2d138380-ec6f-11ea-8f2d-b67fd4af1dd8.png)

3. In **_Components->TO0 scheduler->to0serviceimpl:_**

The third line has T00 instead of TO0

![image](https://user-images.githubusercontent.com/68280628/91841251-a6ab7180-ec6f-11ea-97bb-8e08e6e35256.png)

4. In **_Components->OPS:_**

The First line has T02 instead of TO2

![image](https://user-images.githubusercontent.com/68280628/91841349-d2c6f280-ec6f-11ea-900e-e9d0fb346abd.png)

5. **_In Components->OPS->restimpl_**

The third line has call toOCS. Space required. Should be to OCS

![image](https://user-images.githubusercontent.com/68280628/91841461-0b66cc00-ec70-11ea-8538-eafa3cf668b6.png)

**Section: Development Environment Specifications:**

Table 1. Development Environment Specifications
			Docker versions can be changed.

![image](https://user-images.githubusercontent.com/68280628/91841807-9b0c7a80-ec70-11ea-8a62-8f0b0f115264.png)

**Comment by prateekcr** [comment]
Docker versions are aligned with the versions mentioned in README and the upcoming Installation guide.
Rest have been fixed in commit b5656e9778e25b2c3de4553d2ccdda7db4b1fb40 of PR https://github.com/secure-device-onboard/docs/pull/6.
