### ISSUE TITLE
[IOT Platform SDK] Issues in running-the-demo.md

### ISSUE THREAD

**Issue by himanshu7196** [secure-device-onboard/docs#31]
**_Section: Running The Demo: -> Setting up Resources for OCS_**
Link: https://secure-device-onboard.github.io/docs/latest/iot-platform-sdk/running-the-demo/#setting-up-resources-for-ocs

The last, 3rd last and 4th last paragraph has directory  "\/demo/ocs/config/db/v1/devices". The directory has an extra character/Not rendering properly

![image](https://user-images.githubusercontent.com/68280628/91842486-c5ab0300-ec71-11ea-9e21-6324a93e6eaf.png)

![image](https://user-images.githubusercontent.com/68280628/91842531-dce9f080-ec71-11ea-880a-6d54a1a0e665.png)

**Comment by prateekcr** [comment]
Fixed in PR https://github.com/secure-device-onboard/docs/pull/12/
