### ISSUE TITLE
[IOT Platform SDK] Issues in the development-guide.md

### ISSUE THREAD

**Issue by himanshu7196** [secure-device-onboard/docs#33]
**_Section: Rest Contracts between OCS (server) and OPS/To0Scheduler (client):_**
Link:https://secure-device-onboard.github.io/docs/latest/iot-platform-sdk/development-guide/#rest-contracts-between-ocs-server-and-opsto0scheduler-client

In second line " Both OPS and To0Scheduler makes...". Should be make instead.

![image](https://user-images.githubusercontent.com/68280628/91842991-9943b680-ec72-11ea-842d-062056450211.png)

	
**_Section: Rest Contracts between To0Scheduler (server) and OCS (client)_**
Link:https://secure-device-onboard.github.io/docs/latest/iot-platform-sdk/development-guide/#rest-contracts-between-to0scheduler-server-and-ocs-client

In first line "implementation must, also, acta as a client to trigger TO0 ", implementation must also act as a is mispelled

![image](https://user-images.githubusercontent.com/68280628/91843095-c3957400-ec72-11ea-83c1-4364972f873c.png)

	
**_Section: Message Types:_**
Link:https://secure-device-onboard.github.io/docs/latest/iot-platform-sdk/development-guide/#message-types

In third line of the first paragraph "JavaScript Object Notation (JSON), represents the purpose of the field." should be represent
	
![image](https://user-images.githubusercontent.com/68280628/91843239-11aa7780-ec73-11ea-91e9-829bec685516.png)

**_Section: Message Types -> ModuleMessage:_**
Link:https://secure-device-onboard.github.io/docs/latest/iot-platform-sdk/development-guide/#modulemessage

Second line, extra commas in "...store,both,the device's serviceinfo, and...."

![image](https://user-images.githubusercontent.com/68280628/91843336-41597f80-ec73-11ea-8494-a0658ee003c7.png)

	
**_Section: Message Types -> Message47Store:_**
Link: https://secure-device-onboard.github.io/docs/latest/iot-platform-sdk/development-guide/#message47store

First line: "...temporarily, untill till the". Till is repetitive.

![image](https://user-images.githubusercontent.com/68280628/91843476-6a7a1000-ec73-11ea-8656-4e8dab08283a.png)

**Comment by prateekcr** [comment]
The highlighted 'Statements' seems correct to me.
Rest have been fixed in commit b5656e9778e25b2c3de4553d2ccdda7db4b1fb40 of PR https://github.com/secure-device-onboard/docs/pull/6
