### ISSUE TITLE
[Client SDK]Grammar Corrections Required

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/docs#34]
Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/
Section Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#module-errors
Replace "The Application will need to retry onboarding at a later time. " with "The Application will need to retry onboarding later."[First Paragraph]
<img width="532" alt="ModuleErrors" src="https://user-images.githubusercontent.com/69335071/91842814-541f8480-ec72-11ea-84b9-c970a104f155.png">

Section Link: https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#pre-service-info-psi
Replace: "A failure response will cause the entire onboarding sequence to fail and the Application must retry it at a later time." with "A failure response will cause the entire onboarding sequence to fail and the Application must retry it later."[third paragraph]
<img width="533" alt="PSIChange" src="https://user-images.githubusercontent.com/69335071/91842864-64cffa80-ec72-11ea-9c19-c9bee60a87c9.png">

Section Link :https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#device-service-info-dsi
Replace "The sv.key must strictly be an NULL terminated ASCII string. " with "The sv.key must strictly be a NULL terminated ASCII string. "[fourth paragraph]
<img width="476" alt="Changeantoa" src="https://user-images.githubusercontent.com/69335071/91843134-db6cf800-ec72-11ea-8a36-43d1b22b54ca.png">

Section Link :https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#owner-service-info-osi
Replace "The sv.key must strictly be an NULL terminated ASCII string. " with "The sv.key must strictly be a NULL terminated ASCII string. "[second paragraph]
<img width="532" alt="Changeantoa2" src="https://user-images.githubusercontent.com/69335071/91843382-4f0f0500-ec73-11ea-9f8f-fbfd5a50e0ad.png">

Section Link:https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#module-errors
Replace "hash verification, malformed messages and also if a module returns a failure while processing a PSI, DSI, or OSI command/request." with "hash verification, malformed messages and if a module returns a failure while processing a PSI, DSI, or OSI command/request."[first paragraph]
<img width="544" alt="Changeandalsotoand" src="https://user-images.githubusercontent.com/69335071/91843701-ce9cd400-ec73-11ea-97cf-138b4eb65281.png">

Section Link:https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-reference-guide/#device-service-info-dsi
Replace "It is assumed that the Owner Server knows how to interpret a particular key-value from a particular module. " with "It is assumed that the Owner Server knows how to interpret a particular key-value from a module. ".[fifth paragraph]
<img width="548" alt="Changeaparticularmoduletomodule" src="https://user-images.githubusercontent.com/69335071/91844702-8bdbfb80-ec75-11ea-9d6d-27a26745db3c.png">

Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-api-reference/
Section Link:https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-api-reference/#execute-sdo-sdk-onboarding-protocol
Replace "Additionally, module-specific callbacks will be invoked when Service Information is received from the Owner Server during the course of the TO2 stage." with "Additionally, module-specific callbacks will be invoked when Service Information is received from the Owner Server during the TO2 stage. ".
<img width="514" alt="change1" src="https://user-images.githubusercontent.com/69335071/91845681-2ee14500-ec77-11ea-97b6-4d68bdff76ab.png">

Section Link:https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-api-reference/#error-handling-callback
Replace " It is advisable to abort the operation and retry at a later time." with " It is advisable to abort the operation and retry later.".
<img width="539" alt="change2" src="https://user-images.githubusercontent.com/69335071/91845930-ad3de700-ec77-11ea-96fe-2b32f4968cab.png">

Section Link : https://secure-device-onboard.github.io/docs/latest/client-sdk/client-sdk-api-reference/#error-handling-callback
Replace "The Application can re-invoke this API at a later time to re-initiate the SDO onboarding process." with "The Application can re-invoke this API later to re-initiate the SDO onboarding process.".[Within errorcode]
<img width="509" alt="Change3" src="https://user-images.githubusercontent.com/69335071/91847479-14f43200-ec78-11ea-92ca-cbc15c1e3564.png">

**Comment by nbmaiti** [comment]
- #39
